//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErgasiaMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class author
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public author()
        {
            this.titleauthors = new HashSet<titleauthor>();
        }
    
        [Required, Display(Name = "ID")]
        [RegularExpression(@"\d{3}-\d{2}-\d{4}", ErrorMessage = "ID must be in the form 'ddd-dd-dddd', where d is a digit")]
        public string au_id { get; set; }
        [Required, Display(Name = "Last name")]
        public string au_lname { get; set; }
        [Required, Display(Name = "First name")]
        public string au_fname { get; set; }
        [Required, Display(Name = "Phone"), MaxLength(12)]
        public string phone { get; set; }
        [Required, Display(Name = "Address"), MaxLength(40)]
        public string address { get; set; }
        [Required, Display(Name = "City"), MaxLength(20)]
        public string city { get; set; }
        [Required, Display(Name = "State"), MaxLength(2)]
        public string state { get; set; }
        [Required, Display(Name = "ZIP")]
        [RegularExpression(@"\d{5}", ErrorMessage = "ZIP must be a 5-digit number")]
        public string zip { get; set; }
        [Required, Display(Name = "Contract")]
        public bool contract { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<titleauthor> titleauthors { get; set; }
    }
}
