//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErgasiaMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class employee
    {
        [Required, Display(Name = "ID")]
        [RegularExpression(@"([A-Z]{3}|[A-Z]-[A-Z])[1-9][0-9]{4}[FM]", ErrorMessage = "ID must be in the form '[A-Z][A-Z][A-Z][1-9][0-9][0-9][0-9][0-9][FM]' or '[A-Z]-[A-Z][1-9][0-9][0-9][0-9][0-9][FM]'")]
        public string emp_id { get; set; }
        [Required, DisplayName("First name"), MaxLength(20)]
        public string fname { get; set; }
        [DisplayName("Middle name"), MaxLength(1)]
        public string minit { get; set; }
        [Required, DisplayName("Last name"), MaxLength(30)]
        public string lname { get; set; }
        [DisplayName("Job")]
        public short job_id { get; set; }
        [DisplayName("Job level")]
        public Nullable<byte> job_lvl { get; set; }
        [DisplayName("Publisher")]
        public string pub_id { get; set; }
        [DisplayName("Hired on day")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        [DataType(DataType.Date)]
        public System.DateTime hire_date { get; set; }
    
        public virtual job job { get; set; }
        public virtual publisher publisher { get; set; }
    }
}
