//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErgasiaMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class publisher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public publisher()
        {
            this.employees = new HashSet<employee>();
            this.titles = new HashSet<title>();
        }

        [Required, DisplayName("ID")]
        [RegularExpression(@"99[0-9][0-9]", ErrorMessage = "ID must be in the form '99[0-9][0-9]'")]
        public string pub_id { get; set; }
        [DisplayName("Publisher"), MaxLength(40)]
        public string pub_name { get; set; }
        [DisplayName("City"), MaxLength(20)]
        public string city { get; set; }
        [DisplayName("State"), MaxLength(2)]
        public string state { get; set; }
        [DisplayName("Country"), MaxLength(30)]
        public string country { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee> employees { get; set; }
        [DisplayName("Info")]
        public virtual pub_info pub_info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<title> titles { get; set; }
    }
}
