//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErgasiaMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class store
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public store()
        {
            this.sales = new HashSet<sale>();
            this.discounts = new HashSet<discount>();
        }

        [Required, Display(Name = "ID")]
        public string stor_id { get; set; }
        [Required, DisplayName("Store"), MaxLength(40)]
        public string stor_name { get; set; }
        [Required, DisplayName("Address"), MaxLength(40)]
        public string stor_address { get; set; }
        [Required, DisplayName("City"), MaxLength(20)]
        public string city { get; set; }
        [Required, DisplayName("State"), MaxLength(2)]
        public string state { get; set; }
        [Required, DisplayName("ZIP")]
        [RegularExpression(@"\d{5}", ErrorMessage = "ZIP must be a 5-digit number")]
        public string zip { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sale> sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<discount> discounts { get; set; }
    }
}
