//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErgasiaMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class title
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public title()
        {
            this.sales = new HashSet<sale>();
            this.titleauthors = new HashSet<titleauthor>();
        }

        [Required, Display(Name = "ID")]
        public string title_id { get; set; }
        [Required, DisplayName("Title"), MaxLength(80)]
        public string title1 { get; set; }
        [DisplayName("Type"), MaxLength(12)]
        public string type { get; set; }
        [Required, DisplayName("Publisher"), MaxLength(4)]
        public string pub_id { get; set; }
        [DisplayName("Price"), DataType(DataType.Currency)]
        public Nullable<decimal> price { get; set; }
        [DisplayName("Advance"), DataType(DataType.Currency)]
        public Nullable<decimal> advance { get; set; }
        [DisplayName("Royalty")]
        public Nullable<int> royalty { get; set; }
        [DisplayName("YTD sales")]
        public Nullable<int> ytd_sales { get; set; }
        [DisplayName("Notes"), MaxLength(200)]
        public string notes { get; set; }
        [DisplayName("Publish day")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        [DataType(DataType.Date)]
        public System.DateTime pubdate { get; set; }
    
        public virtual publisher publisher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sale> sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DisplayName("Authors")]
        public virtual ICollection<titleauthor> titleauthors { get; set; }
        public virtual roysched roysched { get; set; }
    }
}
